config/routes.rb
Rails.application.routes.draw do

   root 'galleries#index'

  resources :galleries do
    resources :pictures
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :pictures
end

app/models/artistgallery.rb
class Artistgallery < ActiveRecord::Base
  belongs_to :artist
  belongs_to :gallery
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :pictures
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :gallery
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      flash[:notice] = "Gallery created"
      redirect_to galleries_path
    else
      render :new 
    end
  end

  def show
    @gallery = Gallery.find_by(id: params[:id])
  end
  protected

  def gallery_params
    params.require(:gallery).permit(:title)
  end

end

app/controllers/gallery_controllers.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      flash[:notice] = "Gallery created"
      redirect_to gallery_pictures_path(@gallery)
    else
      render :new 
    end
  end

  def show
    @gallery = Gallery.find_by(id: params[:id])
  end
  protected

  def gallery_params
    params.require(:gallery).permit(:title)
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def new
    @gallery = Gallery.find(params[:gallery_id])
    @picture = Picture.new
  end

  def create
    @gallery = Gallery.find(params[:gallery_id])
    @picture = Picture.new(picture_params)
    @picture.gallery = @gallery
    if @picture.save
      flash[:notice] = "Picture Added"
      redirect_to gallery_pictures_path(@gallery)
    else
      render :new
    end
  end

  protected

  def picture_params
    params.require(:picture).permit(:name, :file)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/index.html.erb
<h3>Index of All Galleries</h3>

<%= link_to 'Create New Gallery', new_gallery_path %>

<div class="row">
  <ul class="small-block-grid-3">
    <% @galleries.each do |gallery| %>
      <li><%= gallery.title %></li>
    <% end %>
  </ul>
</div>

app/views/galleries/new.html.erb
<div class="row">  
  <div class="large-12">
    <%= form_for @gallery do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.submit "Add Gallery" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">Art Gallery</a></h1>
        </li>
      </ul>
    </nav> 

    <%= yield %>

  </body>
</html>

app/views/pictures/index.html.erb
<h1> Pictures </h1>